# Generated by Django 2.0.4 on 2018-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_tag', models.CharField(max_length=30)),
                ('analysis_tweets', models.CharField(max_length=3000)),
            ],
        ),
    ]
