# Generated by Django 2.0.4 on 2018-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_summarization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
